import type { Metadata } from "next";
import "./globals.css";
import Providers from "./providers";
import SmoothScrolling from "./components/smooth-scrolling";
import { Provider } from "@/components/provider";

export const metadata: Metadata = {
  title: "E-Do Studio | Welcome !",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <SmoothScrolling>
          <Providers>
            <Provider>{children}</Provider>
          </Providers>
        </SmoothScrolling>
      </body>
    </html>
  );
}
