import type { Metadata } from "next";
import "./globals.css";
import { Header } from "@/app/ui/layout/header";
import Providers from "./providers";
import SmoothScrolling from "./components/smooth-scrolling";

export const metadata: Metadata = {
  title: "E-Do Studio | Welcome !",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <SmoothScrolling>
          <Providers>
            <main className="flex flex-col absolute w-full">
              <Header />
              {children}
            </main>
          </Providers>
        </SmoothScrolling>
      </body>
    </html>
  );
}
